{
 "title": "Application Observability",
 "tags": [
  "observability",
  "lab"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request rate (req/s) by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(app_requests_total[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "increase(app_errors_total[1m])", "legendFormat": "errors/min" }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(app_requests_total)", "legendFormat": "requests" }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "targets": [
    { "expr": "sum(app_errors_total)", "legendFormat": "errors" }
   ]
  },
  {
   "title": "Application logs (JSON)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{container=\"app\"}"
    }
   ]
  }
 ]
}